/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package htmlparser;
import com.others.Login;
import com.parser.menu.About;
import com.parser.menu.Database;
import com.parser.menu.UserDB;
import static htmlparser.Parser.getPercentage_count;
import java.sql.SQLException;
import java.util.ArrayList;
import java.util.logging.Level;
import java.util.logging.Logger;

/**
 *
 * @author admin
 */
public class ParserFrom extends javax.swing.JFrame {

    /**
     * Creates new form ParserFrom
     */
    public ParserFrom() {
        initComponents();
    }
        private ArrayList<String> List;
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel2 = new javax.swing.JLabel();
        link_parse = new javax.swing.JTextField();
        Button_parse = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();
        jMenuBar1 = new javax.swing.JMenuBar();
        file_menu = new javax.swing.JMenu();
        edit_menu = new javax.swing.JMenu();
        edit_database = new javax.swing.JMenuItem();
        help_menu = new javax.swing.JMenu();
        Info_sub_menu = new javax.swing.JMenuItem();
        about_sub_menu = new javax.swing.JMenuItem();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jLabel2.setFont(new java.awt.Font("Times New Roman", 0, 24)); // NOI18N
        jLabel2.setText("Link");

        link_parse.setFont(new java.awt.Font("Times New Roman", 0, 18)); // NOI18N
        link_parse.setText("Put here the limk from browser");

        Button_parse.setFont(new java.awt.Font("Times New Roman", 0, 24)); // NOI18N
        Button_parse.setText("Parse");
        Button_parse.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                Button_parseActionPerformed(evt);
            }
        });

        jLabel1.setFont(new java.awt.Font("Tahoma", 0, 24)); // NOI18N
        jLabel1.setText("Your Link");

        file_menu.setText("File");
        file_menu.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        jMenuBar1.add(file_menu);

        edit_menu.setText("Edit");
        edit_menu.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N

        edit_database.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        edit_database.setText("Database");
        edit_database.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                edit_databaseActionPerformed(evt);
            }
        });
        edit_menu.add(edit_database);

        jMenuBar1.add(edit_menu);

        help_menu.setText("Help");
        help_menu.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N

        Info_sub_menu.setAccelerator(javax.swing.KeyStroke.getKeyStroke(java.awt.event.KeyEvent.VK_H, 0));
        Info_sub_menu.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        Info_sub_menu.setText("Info");
        help_menu.add(Info_sub_menu);

        about_sub_menu.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        about_sub_menu.setText("About");
        about_sub_menu.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                about_sub_menuActionPerformed(evt);
            }
        });
        about_sub_menu.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                about_sub_menuKeyPressed(evt);
            }
        });
        help_menu.add(about_sub_menu);

        jMenuBar1.add(help_menu);

        setJMenuBar(jMenuBar1);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 74, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(link_parse, javax.swing.GroupLayout.PREFERRED_SIZE, 504, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(Button_parse))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(25, 25, 25)
                        .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 492, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(17, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(49, 49, 49)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(link_parse, javax.swing.GroupLayout.PREFERRED_SIZE, 36, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(Button_parse))
                    .addComponent(jLabel2))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 189, Short.MAX_VALUE)
                .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 52, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(28, 28, 28))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void about_sub_menuKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_about_sub_menuKeyPressed
         
         
    }//GEN-LAST:event_about_sub_menuKeyPressed

    private void about_sub_menuActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_about_sub_menuActionPerformed
        new About().setVisible(true);
    }//GEN-LAST:event_about_sub_menuActionPerformed

    private void edit_databaseActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_edit_databaseActionPerformed
          new Database().setVisible(true);
          
    }//GEN-LAST:event_edit_databaseActionPerformed

    private void Button_parseActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Button_parseActionPerformed
              Parser data = new Parser();
                String url_link = link_parse.getText();
                jLabel1.setText(url_link);
                
        try {
            data.ParseLink(url_link);
        } catch (InstantiationException ex) {
            Logger.getLogger(ParserFrom.class.getName()).log(Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            Logger.getLogger(ParserFrom.class.getName()).log(Level.SEVERE, null, ex);
        } catch (ClassNotFoundException ex) {
            Logger.getLogger(ParserFrom.class.getName()).log(Level.SEVERE, null, ex);
        } catch (SQLException ex) {
            Logger.getLogger(ParserFrom.class.getName()).log(Level.SEVERE, null, ex);
        }
    }//GEN-LAST:event_Button_parseActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(ParserFrom.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(ParserFrom.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(ParserFrom.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(ParserFrom.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new ParserFrom().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton Button_parse;
    private javax.swing.JMenuItem Info_sub_menu;
    private javax.swing.JMenuItem about_sub_menu;
    private javax.swing.JMenuItem edit_database;
    private javax.swing.JMenu edit_menu;
    private javax.swing.JMenu file_menu;
    private javax.swing.JMenu help_menu;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JMenuBar jMenuBar1;
    private javax.swing.JTextField link_parse;
    // End of variables declaration//GEN-END:variables
}
